# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'characteristic.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Characteristic(object):
    def setupUi(self, Characteristic):
        Characteristic.setObjectName("Characteristic")
        Characteristic.resize(752, 137)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Characteristic)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget_30 = QtWidgets.QWidget(Characteristic)
        font = QtGui.QFont()
        font.setPointSize(36)
        self.widget_30.setFont(font)
        self.widget_30.setStyleSheet("border-radius: 8px;\n"
"background-color:rgb(248, 249, 251);\n"
"color: rgb(140, 139, 139);")
        self.widget_30.setObjectName("widget_30")
        self.horizontalLayout_57 = QtWidgets.QHBoxLayout(self.widget_30)
        self.horizontalLayout_57.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout_57.setObjectName("horizontalLayout_57")
        self.name_quality = QtWidgets.QLabel(self.widget_30)
        self.name_quality.setMinimumSize(QtCore.QSize(0, 0))
        self.name_quality.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.name_quality.setFont(font)
        self.name_quality.setStyleSheet("background-color:rgb(248, 249, 251);\n"
"color: rgb(0, 0, 0);\n"
"")
        self.name_quality.setInputMethodHints(QtCore.Qt.ImhNone)
        self.name_quality.setWordWrap(True)
        self.name_quality.setObjectName("name_quality")
        self.horizontalLayout_57.addWidget(self.name_quality)
        self.value_quality = QtWidgets.QLineEdit(self.widget_30)
        self.value_quality.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(22)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.value_quality.setFont(font)
        self.value_quality.setStyleSheet("background-color:rgb(248, 249, 251);\n"
"color: rgb(140, 139, 139);\n"
"outline: 0px;\n"
"padding-left: 10px;\n"
"margin-left: 20px;\n"
"margin-right: 5px;\n"
"border-top-left-radius: 0px;\n"
"border-bottom-left-radius: 00px;\n"
"border: none;\n"
"\n"
"")
        self.value_quality.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.value_quality.setObjectName("value_quality")
        self.horizontalLayout_57.addWidget(self.value_quality)
        self.dimension_quality = QtWidgets.QLabel(self.widget_30)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.dimension_quality.setFont(font)
        self.dimension_quality.setStyleSheet("margin-right: 10px;\n"
"")
        self.dimension_quality.setObjectName("dimension_quality")
        self.horizontalLayout_57.addWidget(self.dimension_quality)
        self.clean_quality = QtWidgets.QPushButton(self.widget_30)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.clean_quality.setFont(font)
        self.clean_quality.setStyleSheet("QPushButton {\n"
"background-color:rgb(138, 161, 233);\n"
"color:rgb(255, 255, 255);\n"
"font-weight: 600;\n"
"border-radius: 8px;\n"
"padding: 5px 15px;\n"
"outline: 0px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(125, 143, 202);\n"
"}")
        self.clean_quality.setObjectName("clean_quality")
        self.horizontalLayout_57.addWidget(self.clean_quality)
        self.horizontalLayout.addWidget(self.widget_30)

        self.retranslateUi(Characteristic)
        QtCore.QMetaObject.connectSlotsByName(Characteristic)

    def retranslateUi(self, Characteristic):
        _translate = QtCore.QCoreApplication.translate
        Characteristic.setWindowTitle(_translate("Characteristic", "Form"))
        self.name_quality.setText(_translate("Characteristic", "Свойство"))
        self.value_quality.setPlaceholderText(_translate("Characteristic", "0"))
        self.dimension_quality.setText(_translate("Characteristic", "°C"))
        self.clean_quality.setText(_translate("Characteristic", "-"))
