# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'color.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Color_form(object):
    def setupUi(self, Color_form):
        Color_form.setObjectName("Color_form")
        Color_form.resize(378, 151)
        Color_form.setStyleSheet("background-color:rgb(240, 241, 242)")
        self.centralwidget = QtWidgets.QWidget(Color_form)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_12 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_12.setStyleSheet("background-color:rgb(0, 0, 0);\n"
"border-radius: 8px;\n"
"padding: 5px 15px;\n"
"outline: 0px;")
        self.pushButton_12.setObjectName("pushButton_12")
        self.gridLayout.addWidget(self.pushButton_12, 3, 4, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setStyleSheet("background-color:rgb(255, 255, 0);\n"
"border-radius: 8px;\n"
"padding: 5px 15px;\n"
"outline: 0px;")
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout.addWidget(self.pushButton_4, 1, 3, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setStyleSheet("background-color:rgb(0, 0, 0);\n"
"border-radius: 8px;\n"
"padding: 5px 15px;\n"
"outline: 0px;")
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout.addWidget(self.pushButton_5, 2, 3, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setStyleSheet("background-color:rgb(0, 0, 0);\n"
"border-radius: 8px;\n"
"padding: 5px 15px;\n"
"outline: 0px;")
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 2, 2, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setStyleSheet("background-color:rgb(0, 0, 0);\n"
"border-radius: 8px;\n"
"padding: 5px 15px;\n"
"outline: 0px;")
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 3, 3, 1, 1)
        self.blue = QtWidgets.QPushButton(self.centralwidget)
        self.blue.setStyleSheet("background-color:rgb(0, 85, 255);\n"
"border-radius: 8px;\n"
"padding: 5px 15px;\n"
"outline: 0px;")
        self.blue.setText("")
        self.blue.setObjectName("blue")
        self.gridLayout.addWidget(self.blue, 1, 2, 1, 1)
        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8.setStyleSheet("background-color:rgb(0, 0, 0);\n"
"border-radius: 8px;\n"
"padding: 5px 15px;\n"
"outline: 0px;")
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout.addWidget(self.pushButton_8, 2, 4, 1, 1)
        self.pushButton_10 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_10.setStyleSheet("background-color:rgb(0, 0, 0);\n"
"border-radius: 8px;\n"
"padding: 5px 15px;\n"
"outline: 0px;")
        self.pushButton_10.setObjectName("pushButton_10")
        self.gridLayout.addWidget(self.pushButton_10, 1, 5, 1, 1)
        self.pushButton_9 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_9.setStyleSheet("background-color:rgb(0, 0, 0);\n"
"border-radius: 8px;\n"
"padding: 5px 15px;\n"
"outline: 0px;")
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout.addWidget(self.pushButton_9, 3, 5, 1, 1)
        self.pushButton_11 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_11.setStyleSheet("background-color:rgb(0, 0, 0);\n"
"border-radius: 8px;\n"
"padding: 5px 15px;\n"
"outline: 0px;")
        self.pushButton_11.setObjectName("pushButton_11")
        self.gridLayout.addWidget(self.pushButton_11, 2, 5, 1, 1)
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setStyleSheet("background-color:rgb(0, 0, 0);\n"
"border-radius: 8px;\n"
"padding: 5px 15px;\n"
"outline: 0px;")
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout.addWidget(self.pushButton_7, 1, 4, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setStyleSheet("background-color:rgb(0, 0, 0);\n"
"border-radius: 8px;\n"
"padding: 5px 15px;\n"
"outline: 0px;")
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout.addWidget(self.pushButton_6, 3, 2, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton {\n"
"background-color:rgb(138, 161, 233);\n"
"color:rgb(255, 255, 255);\n"
"border-radius: 8px;\n"
"padding: 5px 15px;\n"
"outline: 0px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(125, 143, 202);\n"
"}\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 4, 5, 1, 1)
        Color_form.setCentralWidget(self.centralwidget)

        self.retranslateUi(Color_form)
        QtCore.QMetaObject.connectSlotsByName(Color_form)

    def retranslateUi(self, Color_form):
        _translate = QtCore.QCoreApplication.translate
        Color_form.setWindowTitle(_translate("Color_form", "MainWindow"))
        self.pushButton_12.setText(_translate("Color_form", "PushButton"))
        self.pushButton_5.setText(_translate("Color_form", "PushButton"))
        self.pushButton_2.setText(_translate("Color_form", "PushButton"))
        self.pushButton_3.setText(_translate("Color_form", "PushButton"))
        self.pushButton_8.setText(_translate("Color_form", "PushButton"))
        self.pushButton_10.setText(_translate("Color_form", "PushButton"))
        self.pushButton_9.setText(_translate("Color_form", "PushButton"))
        self.pushButton_11.setText(_translate("Color_form", "PushButton"))
        self.pushButton_6.setText(_translate("Color_form", "PushButton"))
        self.pushButton.setText(_translate("Color_form", "Закрыть"))
