# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'device_charat.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(886, 300)
        self.widget_8 = QtWidgets.QWidget(Form)
        self.widget_8.setGeometry(QtCore.QRect(40, 20, 759, 91))
        self.widget_8.setStyleSheet("border-radius: 8px;\n"
"background-color:rgb(248, 249, 251);\n"
"color: rgb(140, 139, 139);\n"
"margin-bottom: 0px;\n"
"margin-top: 0px;\n"
"margin-left: 0px;\n"
"padding: 0;")
        self.widget_8.setObjectName("widget_8")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout(self.widget_8)
        self.horizontalLayout_22.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.name_sub = QtWidgets.QLabel(self.widget_8)
        self.name_sub.setMinimumSize(QtCore.QSize(0, 0))
        self.name_sub.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.name_sub.setFont(font)
        self.name_sub.setStyleSheet("background-color:rgb(248, 249, 251);\n"
"color: rgb(0, 0, 0);\n"
"margin-right: 0px;\n"
"")
        self.name_sub.setInputMethodHints(QtCore.Qt.ImhNone)
        self.name_sub.setWordWrap(True)
        self.name_sub.setObjectName("name_sub")
        self.horizontalLayout_22.addWidget(self.name_sub)
        self.value_sub = QtWidgets.QLineEdit(self.widget_8)
        self.value_sub.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(22)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.value_sub.setFont(font)
        self.value_sub.setStyleSheet("background-color:rgb(248, 249, 251);\n"
"color: rgb(140, 139, 139);\n"
"outline: 0px;\n"
"padding-left: 10px;\n"
"margin-left: 20px;\n"
"margin-right: 20px;\n"
"border-top-left-radius: 0px;\n"
"border-bottom-left-radius: 0px;\n"
"border: none;\n"
"")
        self.value_sub.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.value_sub.setObjectName("value_sub")
        self.horizontalLayout_22.addWidget(self.value_sub)
        self.clean_sub = QtWidgets.QPushButton(self.widget_8)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.clean_sub.setFont(font)
        self.clean_sub.setStyleSheet("QPushButton {\n"
"background-color:rgb(138, 161, 233);\n"
"color:rgb(255, 255, 255);\n"
"font-weight: 600;\n"
"border-radius: 8px;\n"
"padding: 5px 15px;\n"
"outline: 0px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(125, 143, 202);\n"
"}")
        self.clean_sub.setObjectName("clean_sub")
        self.horizontalLayout_22.addWidget(self.clean_sub)
        self.horizontalLayout_22.setStretch(1, 3)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.name_sub.setText(_translate("Form", "Вещество"))
        self.value_sub.setPlaceholderText(_translate("Form", "0"))
        self.clean_sub.setText(_translate("Form", "изменить"))
