# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'device.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_device(object):
    def setupUi(self, device):
        device.setObjectName("device")
        device.resize(973, 97)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(device)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_18 = QtWidgets.QWidget(device)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.widget_18.setFont(font)
        self.widget_18.setStyleSheet("border-radius: 8px;\n"
"background-color:rgb(248, 249, 251);\n"
"")
        self.widget_18.setObjectName("widget_18")
        self.horizontalLayout_35 = QtWidgets.QHBoxLayout(self.widget_18)
        self.horizontalLayout_35.setObjectName("horizontalLayout_35")
        self.check_device = QtWidgets.QCheckBox(self.widget_18)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.check_device.setFont(font)
        self.check_device.setStyleSheet("color:rgb(0, 0, 0)")
        self.check_device.setText("")
        self.check_device.setCheckable(True)
        self.check_device.setChecked(True)
        self.check_device.setAutoRepeatDelay(0)
        self.check_device.setAutoRepeatInterval(0)
        self.check_device.setTristate(False)
        self.check_device.setObjectName("check_device")
        self.horizontalLayout_35.addWidget(self.check_device)
        self.text_device = QtWidgets.QLabel(self.widget_18)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.text_device.setFont(font)
        self.text_device.setWordWrap(True)
        self.text_device.setObjectName("text_device")
        self.horizontalLayout_35.addWidget(self.text_device)
        self.change_btn = QtWidgets.QPushButton(self.widget_18)
        self.change_btn.setStyleSheet("QPushButton {\n"
"background-color:rgb(240, 241, 242);\n"
"color:rgb(255, 255, 255);\n"
"font-weight: 600;\n"
"border-radius: 8px;\n"
"padding: 5px 15px;\n"
"outline: 0px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(125, 143, 202);\n"
"}\n"
"")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/editing.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.change_btn.setIcon(icon)
        self.change_btn.setIconSize(QtCore.QSize(20, 36))
        self.change_btn.setObjectName("change_btn")
        self.horizontalLayout_35.addWidget(self.change_btn)
        self.horizontalLayout_35.setStretch(1, 1)
        self.verticalLayout.addWidget(self.widget_18)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(device)
        QtCore.QMetaObject.connectSlotsByName(device)

    def retranslateUi(self, device):
        _translate = QtCore.QCoreApplication.translate
        device.setWindowTitle(_translate("device", "Form"))
        self.text_device.setText(_translate("device", "TextLabel"))

