# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'type_water_right.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_water_right(object):
    def setupUi(self, water_right):
        water_right.setObjectName("water_right")
        water_right.resize(673, 143)
        water_right.setStyleSheet("")
        self.horizontalLayout = QtWidgets.QHBoxLayout(water_right)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalWidget = QtWidgets.QWidget(water_right)
        self.horizontalWidget.setStyleSheet("background-color:rgb(248, 249, 251);\n"
"color: rgb(0, 0, 0);")
        self.horizontalWidget.setObjectName("horizontalWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalWidget)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.name_water = QtWidgets.QLabel(self.horizontalWidget)
        self.name_water.setMinimumSize(QtCore.QSize(0, 0))
        self.name_water.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.name_water.setFont(font)
        self.name_water.setStyleSheet("background-color:rgb(248, 249, 251);\n"
"color: rgb(0, 0, 0);\n"
"margin-right: 0px;\n"
"")
        self.name_water.setInputMethodHints(QtCore.Qt.ImhNone)
        self.name_water.setWordWrap(True)
        self.name_water.setObjectName("name_water")
        self.horizontalLayout_2.addWidget(self.name_water)
        self.conc = QtWidgets.QLabel(self.horizontalWidget)
        self.conc.setMinimumSize(QtCore.QSize(0, 0))
        self.conc.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.conc.setFont(font)
        self.conc.setStyleSheet("background-color:rgb(248, 249, 251);\n"
"color: rgb(140, 139, 139);\n"
"margin-right: 0px;\n"
"")
        self.conc.setInputMethodHints(QtCore.Qt.ImhNone)
        self.conc.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.conc.setWordWrap(True)
        self.conc.setObjectName("conc")
        self.horizontalLayout_2.addWidget(self.conc)
        self.conc_2 = QtWidgets.QLabel(self.horizontalWidget)
        self.conc_2.setMinimumSize(QtCore.QSize(0, 0))
        self.conc_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.conc_2.setFont(font)
        self.conc_2.setStyleSheet("background-color:rgb(248, 249, 251);\n"
"color: rgb(140, 139, 139);\n"
"margin-right: 0px;\n"
"")
        self.conc_2.setInputMethodHints(QtCore.Qt.ImhNone)
        self.conc_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.conc_2.setWordWrap(True)
        self.conc_2.setObjectName("conc_2")
        self.horizontalLayout_2.addWidget(self.conc_2)
        self.horizontalLayout_2.setStretch(0, 5)
        self.horizontalLayout.addWidget(self.horizontalWidget)

        self.retranslateUi(water_right)
        QtCore.QMetaObject.connectSlotsByName(water_right)

    def retranslateUi(self, water_right):
        _translate = QtCore.QCoreApplication.translate
        water_right.setWindowTitle(_translate("water_right", "Form"))
        self.name_water.setText(_translate("water_right", "Вода"))
        self.conc.setText(_translate("water_right", "Концентрация"))
        self.conc_2.setText(_translate("water_right", "мг/л"))
